# Generated by Django 4.2 on 2024-04-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0002_rename_tortas_torta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torta',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
