# Generated by Django 4.2 on 2024-04-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0004_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torta',
            name='slug',
            field=models.SlugField(),
        ),
    ]
