# Generated by Django 4.2 on 2024-04-19 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0006_torta_is_featured_torta_price_torta_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupcake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField()),
                ('slug', models.SlugField()),
                ('is_private', models.BooleanField(default=False)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='torta',
            name='torta_uuid',
        ),
        migrations.AddField(
            model_name='torta',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='torta',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
