# Generated by Django 4.2 on 2024-04-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0007_cupcake_remove_torta_torta_uuid_torta_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupcake',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='torta',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
